### ISSUE TITLE
getting text from signs won't work

### ISSUE THREAD

**Issue by JAQUBA** [SkriptLang/Skript#1543]
2.3-alpha3

on click:
  event-block is any sign
  
  send "%first line of event-block%"

---------------
returns "<none>"

**Comment by TheBentoBox** [comment]
I'm trusting that this has been resolved but not properly released yet via @ShaneBeee 's testing.

**Comment by iOshawott** [comment]
Try this when it's placed on wall:
```
on rightclick on sign:
    broadcast "eee"
```
It doesn't works

> on rightclick on wall sign

 This is reloading successfully, but isn't working at all.

**Comment by ShaneBeee** [comment]
@iOshawott 
That is due to the aliases
```
wall sign¦s = minecraft:wall_sign
[floor] sign¦s = minecraft:standing_sign
any sign¦s = wall sign, floor sign
```
"sign" is pointing to floor signs, for a wall sign you would need to type either "wall sign" or "any sign"
maybe what I should do is change it as follows
```
wall sign¦s = minecraft:wall_sign
floor sign¦s = minecraft:standing_sign
[any] sign¦s = wall sign, floor sign
```
this way it would recognize either of the 2 types of signs when using just "sign"

**Comment by iOshawott** [comment]
@ShaneBeee Uhhh I know that but what I don't write wall,floor,any - this still doesn't works if I place it on wall :v

**Comment by ShaneBeee** [comment]
Im aware, because as I JUST said "sign" points to floor signs not wall signs
Thats why when you click on a floor sign it works and not a wall sign.

if I do this it works:
```
on rightclick on wall sign:
    broadcast "eee"
```

Like I said in my previous comment, I was proposing a change to the aliases, which I have already submitted

**Comment by iOshawott** [comment]
Okay but
```
on rightclick on any sign:
	set {_x} to line 2 of event-block
	send "%{_x}%"
```
works on floor signs but not on wall signs. at wall signs I am getting <none>

**Comment by JAQUBA** [comment]
in latest(2.3-beta1) version it working good
Solved for me :)
