### ISSUE TITLE
Disabling variable missing and/or warnings doesn't work

### ISSUE THREAD

**Issue by DDuart** [SkriptLang/Skript#2370]
### Description
After set `disable variable missing and/or warnings:` to  true, there are still warnings 

### Errors / Screenshots

```
[19:15:22] [Server thread/WARN]: [Skript] List is missing 'and' or 'or', defaulting to 'and':
```

### Server Information
* **Server version/platform:**       Paper 1.13.2
* **Skript version:**                Skript 2.4-beta5

**Comment by FranKusmiruk** [comment]
Closing since it

**Comment by Matocolotoe** [comment]
I can confirm this problem, also the warning is taken from the console so he restarted the server.

**Comment by Blueyescat** [comment]
Please explain how can you confirm it

**Comment by FranKusmiruk** [comment]
@Blueyescat most probably with functions, this was fixed by bensku in a recent commit though

**Comment by Matocolotoe** [comment]
It wasn't with functions, also lmao why this question ? I can confirm it because it happened for me too, disabling these warnings and restarting the server does nothing

**Comment by Blueyescat** [comment]
Because the issue can't be solved by thanking you for confirming it.

**Comment by Matocolotoe** [comment]
Sure, but it can't be closed if it happens for other people

**Comment by Blueyescat** [comment]
It can be. Saying "there is a bug" without any detail doesn't help anyone to fix or test it.

**Comment by Blueyescat** [comment]
Okay now i can confirm it with a fresh server, but still works fine in another server that runs with 2.4-beta5 hmm..

1. start a fresh server
2. add test.sk to plugins/Skript/scripts/ with content:
    ```vb
    on load:
    	set {x::*} to 1, 2
    ```
3. reload it, and it will give the warning
4. disable the warning from the config, make sure you saved the file
5. stop and start the server, the warning still happens even when using `/sk reload test` or changing the config again and doing `/sk reload config`.

**Comment by Moderocky** [comment]
This still appears to be ongoing as of the latest version.

It seems to be intermittent as to when it occurs, as most of these are ignored but some of the warnings still appear. From my testing, the longer/more complex the list is, the more likely it is to give a warning.
