### ISSUE TITLE
Async on right click does not work.

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3808]
### Description
The ```on right click on any sign``` does not work but ```on sign change:``` works

### Steps to Reproduce
```
on rightclick on any sign:
	if file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt" is missing:
		create file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	set {_now} to now formatted as "[dd.MM.yyyy HH:mm:ss]"
	set {_loc} to "<x: %x-loc of event-block%; y: %y-loc of event-block%; z: %z-loc of event-block%; świat: %event-block's world%>"
	append "%{_now}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	append "%{_loc}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
    set {_1} to line 1 of clicked block
	append "- %{_1}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
    set {_2} to line 2 of clicked block
	append "- %{_2}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
    set {_3} to line 3 of clicked block
	append "- %{_3}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
    set {_3} to line 4 of clicked block
	append "- %{_4}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
```
### Expected Behavior
The right click does not work. It will output message with warnings (link down) but ```on sign change:``` will work

### Errors / Screenshots
https://pastebin.com/maCDndCr

### Server Information
* **Server version/platform:** This server is running Purpur version git-Purpur-1001 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
* **Skript version:**  Skript version 2.5.3

**Comment by TPGamesNL** [comment]
<details>
  <summary>Code</summary>

```
on sign change:
	if file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt" is missing:
		create file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"
		set {_now} to now formatted as "[dd.MM.yyyy HH:mm:ss]"
		set {_loc} to "<x: %x-loc of event-block%; y: %y-loc of event-block%; z: %z-loc of event-block%; świat: %event-block's world%>"
		append "%{_now}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"
		append "%{_loc}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"
		append "- %line 1%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"
		append "- %line 2%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"
		append "- %line 3%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"
		append "- %line 4%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"
		append "KONIEC" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Nowe tabliczki.txt"

on rightclick on any sign:
	if file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt" is missing:
		create file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
			set {_now} to now formatted as "[dd.MM.yyyy HH:mm:ss]"
			set {_loc} to "<x: %x-loc of event-block%; y: %y-loc of event-block%; z: %z-loc of event-block%; świat: %event-block's world%>"
			append "%{_now}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
			append "%{_loc}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
			append "- %line 1%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
			append "- %line 2%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
			append "- %line 3%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
			append "- %line 4%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
```
</details>

A few things:
1. See here how to format your code properly: https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code
2. Try simplifying and retesting your code before reporting.
3. Try debugging your code to see where exactly the issue lies.
4. Be detailed in telling us what the issue is: 'does not work' isn't good, especially when you've haven't followed the points above ^

**Comment by Misio12320** [comment]
Fixed the issue.
`
on rightclick on any sign:
	if file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt" is missing:
		create file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	set {_now} to now formatted as "[dd.MM.yyyy HH:mm:ss]"
	set {_loc} to "<x: %x-loc of event-block%; y: %y-loc of event-block%; z: %z-loc of event-block%; świat: %event-block's world%>"
	append "%{_now}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	append "%{_loc}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	set {_1} to line 1 of clicked block
	append "- %{_1}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	set {_2} to line 2 of clicked block
	append "- %{_2}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	set {_3} to line 3 of clicked block
	append "- %{_3}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
	set {_4} to line 4 of clicked block
	append "- %{_4}%" to file path "Gracze/Folder Gracza: %player%/Tabliczki gracza/Stare tabliczki.txt"
` this is the code where I debugged. And the result is 
`[12.03.2021 17:12:20]
<x: -12.5; y: 84.5; z: 71.5; świat: world>
- test
- aaa
- xx
- <none>
` last line is missing.
tested one more:
`[12.03.2021 17:12:53]
<x: -12.5; y: 84.5; z: 71.5; świat: world>
- test
- aaa
- <none>
- <none>
` 2 lines are missing.

**Comment by FranKusmiruk** [comment]
Closing as  this is an issue with Skent.

**Comment by Olyno** [comment]
Well, this is not a Skent issue in fact. Skent only executes effects asynchronously. If variables are deleted, it's not related to Skent directly but Skript, and mainly to this issue: #1817
This issue is up since 2 years now, and is not fixed at all. So this issue is valid but just duplicate that's all.

**Comment by TPGamesNL** [comment]
The initial error was an issue with Skent, if anything: when an effect is executed asynchronously, expressions in it are gotten async as well. The expression to get the line on a sign doesn't support being ran async, so it errored. 

The error after that (variables being deleted) is an issue with `AsyncEffect`, as it doesn't implement the new way of doing variables properly.

**Comment by Olyno** [comment]
> The initial error was an issue with Skent, if anything: when an effect is executed asynchronously, expressions in it are gotten async as well. The expression to get the line on a sign doesn't support being ran async, so it errored.
> 
> The error after that (variables being deleted) is an issue with `AsyncEffect`, as it doesn't implement the new way of doing variables properly.

Yes sorry if I misspoke, I was talking about the append effect directly which put "none" in the file

**Comment by AyhamAl-Ali** [comment]
I think [this issue](https://github.com/iBlitzkriegi/Vixio/issues/307) might be related to it?

**Comment by TPGamesNL** [comment]
> I think [this issue](https://github.com/iBlitzkriegi/Vixio/issues/307) might be related to this?

Yes, it's related, but that's just an issue with Vixio, since it isn't up-to-date.

> The error after that (variables being deleted) is an issue with AsyncEffect, as it doesn't implement the new way of doing variables properly.

@Olyno I just looked at the source code of `EffAppendFile`, but it isn't using Skript's `AsyncEffect`, it's a class from Skent:
![image](https://user-images.githubusercontent.com/29547183/111064078-59c41580-84b2-11eb-9018-aa2bf6d11131.png)
so this is still an issue with Skent, not Skript, therefore I'm closing this issue. Any addons that implement async stuff should save the variables before ending the trigger and restore those variables before continuing the trigger.
